### PR TITLE
apply bind to onload

### PR DESCRIPTION
**Pull request by riteshsahu314**

### CODE REVIEW

**Comment by lavrton** [comment]
Why do we need it?

**Comment by riteshsahu314** [comment]
When I made production build of my code, I was getting `img` as undefined inside the `onload` function because of the binding issue (took me a whole day to find that). It was a very weird issue, cause it code was working well on the development environment.

**Comment by lavrton** [comment]
Interesting. I don't see how image can be undefined here. Can you copy minified version of `use-image` lib from production build?

**Comment by riteshsahu314** [comment]
Sure, I will copy that.

**Comment by riteshsahu314** [comment]
This is what I have got:

`function(U,c,t){var e=t(0),a={image:void 0,status:"
loading "};U.exports=function(U,c){var t=e.useState(a),f=t[0].image,d=t[0].status,b=t[1];return e.useEffect(function(){function t(){b({image:f,status:"
loaded "})}function e(){b({image:void 0,status:"
failed "})}if(U){const f=document.createElement("
img ");return f.addEventListener("
load ",t),f.addEventListener("
error ",e),c&&(f.crossOrigin=c),f.src=U,function(){f.removeEventListener("
load ",t),f.removeEventListener("
error ",e),b(a)}}},[U,c]),[f,d]}},function(U,c,t){var e=t(887);"
string "===typeof e&&(e=[[U.i,e,"
"]]);var a={};a.transform=void 0;t(135)(e,a);e.locals&&(U.exports=e.locals)}
`

**Comment by lavrton** [comment]
What tools are you using for making a production build? That looks like a bug in the minifier.

**Comment by lavrton** [comment]
The last version should fix the issue.

**Pull request closed without merging**
